language: python
python:
  - "3.4"
  - "2.7"
before:
  - pip install flake8
  - pip install codecov
  - pip install pytest-cov
  - pip install --upgrade setuptools
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
before_script:
  - flake8 pygram/ tests/ setup.py
script:
  - py.test --cov=. tests/ pygram/
after_success:
  - codecov
