language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before:
  pip install flake8
  pip install codecov
  pip install pytest-cov
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
before_script:
  - flake8 pygram/ tests/ setup.py
script:
  - py.test --cov=pygram tests/
after_success:
  - codecov
